---
- name: Pull web server image
  ansible.builtin.docker_image:
    name: nginx:latest
    source: pull

- name: Run web server container
  ansible.builtin.docker_container:
    name: web_server_{{ item }}
    image: docker.arvancloud.ir/nginx:latest
    state: started
    published_ports:
      - "80:80"
    with_sequence: start=1 end=3

